In [86]:
                                ## Numpy Assignments ##

In [ ]:
import numpy as np


Create an array of 10 zeros

In [81]:
a=np.zeros( 10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create an array of 10 ones

In [85]:
b=np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create an array of 10 fives

In [87]:
b=(np.ones(10))*5
b

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Create an array of the integers from 10 to 50

In [88]:
v=np.arange(10,51)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Create an array of all the even integers from 10 to 50

In [89]:
x=np.arange(10,51,2)
x

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Create a 3x3 matrix with values ranging from 0 to 8

In [27]:
s=np.arange(0,9)
s1=s.reshape(3,3)
s1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
s=np.arange(0,9)
s1=np.matrix(s)
s1.reshape(3,3)

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

Create a 3x3 identity matrix

In [93]:
d=np.eye(3,3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Use NumPy to generate a random number between 0 and 1

In [98]:
s=np.random.rand()
s

0.959551348641022

Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [101]:
s=np.random.randn(25)
s

array([ 1.67250743, -0.38948896,  0.17692271,  2.4168188 , -0.08125374,
       -0.09675763,  1.28697525, -0.77075004,  1.30895852,  0.90290188,
        0.51476743, -1.3619753 , -0.10718965, -0.15122852,  0.84499535,
       -0.99580898, -0.63637343, -0.22890982,  0.53269922,  0.31427146,
       -0.74667175, -1.1701179 , -0.26829607, -1.00829949,  0.59922476])

Create the following matrix:

In [102]:
mat1 = np.arange(0.01,1.01,0.01).reshape(10,10)
mat1

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

Create an array of 20 linearly spaced points between 0 and 1:

In [103]:
c=np.linspace(0,1,20)
c

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [24]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Create an array of 20 linearly spaced points between 0 and 1:

In [49]:
mat[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [54]:
mat[3,4]

20

In [56]:
mat[0:3,[1]]

array([[ 2],
       [ 7],
       [12]])

In [57]:
mat[[4,]]

array([[21, 22, 23, 24, 25]])

In [65]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Get the sum of all the values in mat

In [67]:
mat.sum()

325

Get the standard deviation of the values in mat


In [68]:
mat.std()

7.211102550927978

Get the sum of all the columns in mat


In [106]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])